### ISSUE TITLE
Pedometer not working

### ISSUE THREAD

**Issue by gaetanjung3** [STMicroelectronics/lis2duxs12-pid#4]
I'd like to contact you about one of the examples published by LIS2DUXS12 on GitHub.
 
I can't get any of the pedometer examples to work, with or without FIFO. And on my side it does not work neither on UNICO software. However, the other examples work with interruption in the configuration I have, and on UNICO. I use I2C communication and all commands are ACK. 
If I've understood correctly in the example without FIFO “lis2duxs12_pedometer”, an interrupt must be raised when a number of steps greater than the debounce (set to 4) is detected. On the one hand, no interrupt is raised in this example for me, and periodically reading the lis2duxs12_embedded_status_get register, I never read step_det==1.
I simulate steps by hand, using periodic steps.
I'm using driver v2.2.0, and by the way the lis2duxs12_embedded_int_config_set function is currently lis2duxs12_embedded_int_cfg_set in the driver.
Can you tell me if a special configuration is necessary or if the example works on your side ?
Thank you in advance for your time and help,

**Comment by avisconti** [comment]
Hi,

I tried both lis2duxs12_pedometer.c and lis2duxs12_pedo_fifo.c examples, I used a Nucleo F401RE board, which is already supported in the examples.

What I see on terminal is:

Steps: 5
Steps: 6
Steps: 7
Steps: 8
Steps: 9
Steps: 14
Steps: 15

or (fifo case)

-- 8 in FIFO
Steps: 005 (3159 ms)
Steps: 006 (3487 ms)
Steps: 007 (3896 ms)
Steps: 008 (4224 ms)
Steps: 009 (4633 ms)
Steps: 010 (5043 ms)
Steps: 011 (5453 ms)
Steps: 012 (5780 ms)

-- 8 in FIFO
Steps: 013 (6190 ms)
Steps: 014 (6518 ms)
Steps: 015 (6927 ms)
Steps: 016 (7255 ms)
Steps: 017 (7665 ms)
Steps: 018 (7992 ms)
Steps: 019 (8402 ms)
Steps: 020 (8729 ms)

**Comment by avisconti** [comment]
Some more details for the fifo case (but it is same for the other):

in main.c (generated using CubeMx):

[...]
/* USER CODE BEGIN PFP */
void lis2duxs12_pedo_fifo(void);
void lis2duxs12_pedo_fifo_handler(void);
/* USER CODE END PFP */

/* Private user code ---------------------------------------------------------*/
/* USER CODE BEGIN 0 */
/* overwrite default interrupt callback */
void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin)
{
  lis2duxs12_pedo_fifo_handler();
}

[...]

  /* Infinite loop */
  /* USER CODE BEGIN WHILE */
  while (1)
  {
    /* USER CODE END WHILE */

    /* USER CODE BEGIN 3 */
    lis2duxs12_pedo_fifo();
  }
  /* USER CODE END 3 */

**Comment by gaetanjung3** [comment]
Thank you for your help, it is indeed working now on my side !
Best regards and thank you again, 
Gaétan
