### ISSUE TITLE
BW not properly handled in lis2duxs12_mode_set() 

### ISSUE THREAD

**Issue by miroslavbatek** [STMicroelectronics/lis2duxs12-pid#5]
BW not properly handled in lis2duxs12_mode_set() function. For example the only valid BW for 6Hz LP is ODR/2 which is 0.

![image](https://github.com/user-attachments/assets/c037148d-04da-46f4-a6d3-a13b5b87c628)

![image](https://github.com/user-attachments/assets/a78ff9bb-8014-4c71-b8f3-a6a126d3c2ba)

But according to the datasheet the allowed value is 3.

![image](https://github.com/user-attachments/assets/21a6d537-8f69-4d80-81b5-5e4334d9b39d)

**Comment by avisconti** [comment]
Fixed by 1982b92
